
# The script generates sorted list of vertex similarities given a prediction vector,
# which could also be interpreted as vertex similarity vector. 
# That vector was generated by using logistic regression that in turn had input from a group of vertex similarity measures.

glmSimList <- function(sampledGraph, predictions)
{
	options(error=recover)
	
	
	actual_edgeList <- get.edgelist(sampledGraph)
	nodeCount <- max(actual_edgeList) + 1


	rows <- nodeCount
	cols <- nodeCount


	list <- mat.or.vec(rows * cols, 6)

	i <- 1
	for (row in 1:rows)
	{
		for (col in row:cols)		# assume symmetric matrix
		{
			if (col == row)		# skip self-associations
				next

			
			sim <- predictions[i]
			

			list[i, 1] <- row #- 1	# node indexes are zero-based
			list[i, 2] <- col #- 1	# node indexes are zero-based
			list[i, 3] <- sim

			i <- i + 1
		}
	}

	i <- i - 1			# obtain last used index
	list <- list[1:i, ]		# truncate unused rows
	
	o <- order(list[,3], decreasing = TRUE)		# sort by last column
	list <- list[o,]
				
	list

}
